---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: nginx-ingress
  namespace: default
  labels:
    chart: nginx-ingress
spec:
  chartGitPath: nginx-ingress
  releaseName: nginx-ingress
  values:
    image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.16.2
    imagePullPolicy: IfNotPresent
    controller:
      service:
        type: LoadBalancer
      publishService:
        enabled: true
    rbac:
      create: true