{{- if .Values.ingress.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{.Release.Name}}"
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range $host, $paths := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      {{- range $paths }}
      - path: {{ . }}
        backend:
          serviceName: "{{.Release.Name}}"
          servicePort: {{ .Values.service.externalPort }}
      {{- end -}}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end }}
