apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-config
  namespace: default
spec:
  encryptedData:
    config.json: AgAUbA8EC6oyOmSgyCVhzvgZ1nLz32o3iGMv4m6fYzVw/Gj6yYCV42XBQvGQLjqWTia2/D8vhdDL1H0g41de8JfuVOF/mbWt/wUSO1GsrRpIJwu/gc8Tw0SHqAlAUuTKGVnbmI+UXa5E2MuPOaS2TR3xwPU7aT3nmQZqlm0TTKLQRljvAiV574PX7Lj38ypMx0rA8VorbCsu4+MMzAeAz+GXRj3s2XusxYxhaJu8JNhQ9fZ5TXaHMnKwJ//9MOS7jOpKQm+aLJflHJMEdxJ3ZFL8V1e6JnoTvEOucGfYibkMnp2OA5IfRVHLtixOsX2dghjIPg9z0sqEvwFl3xQvrMB2gBqQpSyW4WFOPV2XVO5L0vVyeCo/h6pWdDN5Ss/9sbUetofcWOrQNqBFqOjhAvqCtP1z97+I1OwoJsEmWMNAu00iTylsdVvHslkQBt0KyoywdwLfy2DWBGwT4FXgi+ETl/YB8TWlPp/UpuegN9jUAsrYO110OMIc+uAjjxIAAh26X4LqgQJvm+r/bkQqjpcRYwTXkdW2uCyuMW3KHCHWS9uD4wMy2YGMFbM41MaECA0kVAx6LH3NvZHzMiIcvQO/0wNy6xkleb8nnYehZslrZmT8rU3kp0OKHZXj9P4l4P6gz/4JReKc+sBQrDDQZnMPsIURNJtOj8RIQuQRaz3IuC5XK2dMYz+vBO40iGh8pSMsGADLRyKjPXGVPT0s4iiYbrm+SB1IhS98+VaCegJELTNVehNbCrnn9P5MLOSGbmJpdv6Nb/zqqz/XCgcG5rLxzgAoOX/MFEH7AaAv2Os14TQwBe/0g+G8Ww8mPFFt6A0XJW5aoGl0xBeN1+Q10QRqHfKOC2em3w1NBNlwzc8K/C1Vx6fZWuGqNc+exNeoEAtm7K4+

