apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockercfgjson: AgCIs8v7MpxUz9vs7H/5wABj7c7MKm1bqxYYsCCFvwTdzIq3rvBA9f2HpV3sKw7OvlH4ikJK0inqzamJVqIIKSBbmViSNNcm3CmFYazhPj9zS475wrSW2wxy/DW3KHqFgpzLjPuDXIH8zB8r9B2oTP9x08NF/r/PLmG8kD+F7Yc0NTApQFB2FDeYqoxUNQfPAjghi8kSiMwE+O11AXRGRhJZ83EXMPy1QEwiwsor7BZrQqn0yqmMvkgYSxLwS2DvOH9DKjWoiHDdI1NRGKGQAZUhpm79AG7Ug1mYDLpgKaoUHJ1pyOC2rR8BcAO5qeCtHzbjRybJzL00MEqUQD96NEyNURtWTZeFL0Rq/CPud/VaZls0VhpDDiP217qMnhMcvtem4pzI62Vc2+RBKnFFsPLVi/CVtzN3wvOHMk0R2wgPB1IcaxThtCFfiITjWZfWeE93HfJ2N3cBee82k1plhBvXThJqqVCv8odBmCqForuXypcThYkwAiw8GnH5hGzRdDOLgsy3STUvcb+G53N0rXM8uiuVl7gH4ZmafCXeRpJoGP2UhgrG7j1fL/lycDx57uKA8Fy+STPAUHqVd0vFHT7k8487niDuy0/9FQZfnKqT4g1YTzH2O2fKHURBSqlqfGMfr3+7JlrlI7Mj5dGWhUI/OweemMW6u+XdBIRkccRd/KdYstZykk9nlnNUvJJxGrXE8dR2soMBdEgTThlgIAq7+Dv7J5w9qPdBiPA1T1+v8BCVB5WHrlVKDA575knsM9PwsIP2hbeqyaGx7FqfZClfM2/DPpfyZ29+EDO6ovulu63vSWD5dPXrkOp5V7cJFWCPwJPbnZed1MD+1MgH

